# Generated by Django 5.0.2 on 2024-02-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryDescription',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_code',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
