# Generated by Django 5.0.2 on 2024-02-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_remove_productimage_product_delete_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
    ]
